create table users
(
    id bigint generated by default as identity primary key,
    name varchar(20),
    email varchar(50),
    avatar_url varchar(250),
    created_at timestamp not null
);

create table brands
(
    id bigint generated by default as identity primary key,
    name varchar(20),
    slug varchar(50),
    description varchar(50),
    logo_url varchar(250),
    website varchar(250)
);

create table sellers
(
    id bigint generated by default as identity primary key,
    name varchar(20),
    description varchar(50),
    logo_url varchar(250),
    rating float not null,
    contact_email varchar(50),
    contact_phone varchar(20),
    created_at timestamp not null
);

create table products
(
    id bigint generated by default as identity primary key,
    name varchar(50),
    slug varchar(50),
    short_description varchar(50),
    full_description varchar(250),
    seller_id bigint references sellers (id),
    brand_id bigint references brands (id),
    status varchar(10),
    created_at timestamp not null,
    updated_at timestamp
);

create table product_details
(
    id bigint generated by default as identity primary key,
    product_id bigint not null references products (id),
    weight float,
    dimensions json,
    materials varchar(50),
    country_of_origin varchar(50),
    warranty_info varchar(50),
    care_instructions varchar(50),
    additional_info jsonb
);

create table product_prices
(
    id bigint generated by default as identity primary key,
    product_id bigint not null references products (id),
    base_price integer not null,
    sale_price integer,
    cost_price integer,
    currency varchar(3) default 'KRW' not null,
    tax_rate integer not null
);

create table categories
(
    id bigint generated by default as identity primary key,
    name varchar(20) not null,
    slug varchar(50),
    description varchar(50),
    parent_id bigint references categories (id),
    level integer not null,
    image_url varchar(250)
);

create table product_categories
(
    id bigint generated by default as identity primary key,
    product_id bigint not null references products (id),
    category_id bigint not null references categories (id),
    is_primary boolean not null
);

create table product_option_groups
(
    id bigint generated by default as identity primary key,
    product_id bigint not null references products (id),
    name varchar(20),
    display_order integer not null
);

create table product_options
(
    id bigint generated by default as identity primary key,
    option_group_id integer not null references product_option_groups (id),
    name varchar(20),
    additional_price integer,
    sku varchar(20) not null,
    stock integer not null,
    display_order integer not null
);

create table product_images
(
    id bigint generated by default as identity primary key,
    product_id bigint not null references products (id),
    url varchar(250),
    alt_text varchar(20),
    is_primary boolean not null,
    display_order integer not null,
    option_id integer references product_options (id)
);

create table tags
(
    id bigint generated by default as identity primary key,
    name varchar(20),
    slug varchar(50)
);

create table product_tags
(
    id bigint generated by default as identity primary key,
    product_id bigint not null references products (id),
    tag_id integer not null references tags (id)
);

create table reviews
(
    id bigint generated by default as identity primary key,
    product_id bigint not null references products (id),
    user_id bigint not null,
    rating float not null,
    title varchar(50),
    content varchar(1000),
    created_at timestamp not null,
    updated_at timestamp,
    verified_purchase boolean not null,
    helpful_votes integer not null
);
